### ISSUE TITLE
Chatterbot Django custom corpus

### ISSUE THREAD

**Issue by BLCKPSTV** [vkosuri/chatterbot-live-example#3]
Hi how do I manage to get a custom corpus file in the same directory of the django project to be read? 

And do I need to change the sql database?

I really want to import my own corpus...

**Comment by vkosuri** [comment]
Use absolute path your corpus file. I tried it is working.

``` Python
CHATTERBOT = {
    'name': 'ADTRAN Chatter Bot',
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
        'data/internal/product/mosaic.corpus.json',
    ],
}
```

**Comment by BLCKPSTV** [comment]
Hey! :) 

I change my code in setting.py to following.
```

CHATTERBOT = {
    'name': 'Theloneliestmonk',
    'logic_adapters' : [
        "chatterbot.logic.MathematicalEvaluation",
        "chatterbot.logic.TimeLogicAdapter",
        "chatterbot.logic.BestMatch"
    ],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
         #'chatterbot.corpus.english',
         #'chatterbot.corpus.english.drugs',
         '/data/english/drugs.corpus.json'
        ]
```

When I started to test it my results where the following.  (I used drugs corpus because of the direct notice of change in answers..)

```
weed
Come stai?
git
how far is the sun
blow
Allora se non puoi leggere, ti chiedo quale è il tuo colore preferito?
marihuana
沒有


```

Do I need to train the chatterbot before pushing heroku master?

**Comment by BLCKPSTV** [comment]
Error code when training.. 

```
 python manage.py train
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/chatterbot/ext/django_chatterbot/management/commands/train.py", line 19, in handle
    chatterbot.train(chatterbot.training_data)
  File "/usr/local/lib/python2.7/site-packages/chatterbot/trainers.py", line 114, in train
    corpus_data = self.corpus.load_corpus(corpus)
  File "/usr/local/lib/python2.7/site-packages/chatterbot_corpus/corpus.py", line 71, in load_corpus
    corpus = self.read_corpus(file_path)
  File "/usr/local/lib/python2.7/site-packages/chatterbot_corpus/corpus.py", line 39, in read_corpus
    with io.open(file_name, encoding='utf-8') as data_file:
IOError: [Errno 2] No such file or directory: '"./data/english/drugs.corpus.json"'

```

**Comment by BLCKPSTV** [comment]
Full Code Setting.py !! 
```
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','fathomless-hollows-49545.herokuapp.com']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'chatterbot.ext.django_chatterbot',
    'example_app',
)

# ChatterBot settings

CHATTERBOT = {
    'name': 'Chatter Bot',
    #'logic_adapters' : [
        #"chatterbot.logic.MathematicalEvaluation",
        #"chatterbot.logic.TimeLogicAdapter",
        #"chatterbot.logic.BestMatch"
    #],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
         #'chatterbot.corpus.english',
         #'chatterbot.corpus.english.drugs',
         '"./data/english/drugs.corpus.json"'

        ]
}

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
)

ROOT_URLCONF = 'example_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'example_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static'),
)

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
```

![schermafbeelding 2017-05-01 om 21 37 30](https://cloud.githubusercontent.com/assets/6031569/25591820/73cfc808-2eb6-11e7-8ad6-43abe329d9db.png)

**Comment by vkosuri** [comment]
Your settings should like this, I am assuming you are using ``Windows``, 

```Python
CHATTERBOT = {
    'name': 'Theloneliestmonk',
    'logic_adapters' : [
        "chatterbot.logic.MathematicalEvaluation",
        "chatterbot.logic.TimeLogicAdapter",
        "chatterbot.logic.BestMatch"
    ],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
         #'chatterbot.corpus.english',
         #'chatterbot.corpus.english.drugs',
         'c:/fath../example_app/data/english/drugs.corpus.json'
        ]
```

**Comment by BLCKPSTV** [comment]
I'm on a mac so it would be '/Users/myname/herokuname/example_app/data/english/drugs.corpus.json'

Tried this and it didn't work still have all the languages and other corpusses..

**Comment by zxxgobig** [comment]
hi , i clone it and run success,but the response is wrong ,i think maybe sqlite field has trouble ,i input "python" chatterbot output "what language are you written in" please check it,thanks!

**Comment by BLCKPSTV** [comment]
I get the same output! But what does that mean, sqlite needs refreshing??

**Comment by vkosuri** [comment]
@BLCKPSTV @zxxgobig I think the latest version of chatterbot will solve many problems. I need to update package version soon.
